# Generated by Django 2.2.1 on 2019-09-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20190912_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=8),
        ),
    ]
