# Generated by Django 2.2.1 on 2019-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '游客'), (2, '博主')], default=1),
        ),
    ]
