# Generated by Django 2.2.1 on 2019-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@qq.com', max_length=254),
            preserve_default=False,
        ),
    ]
